export const DID_YOU_KNOW = [
  "Bal asla bozulmayan tek yiyecektir; arkeologlar Mısır mezarlarında 3000 yıllık yenilebilir bal bulmuşlardır.",
  "Ahtapotların üç kalbi ve dokuz beyni vardır.",
  "İnsan vücudundaki kan damarlarının toplam uzunluğu dünyayı iki buçuk kez dolaşabilir.",
  "Bir salyangoz üç yıl boyunca uyuyabilir.",
  "Muzlar aslında bir tür çilektir, ancak çilekler çilek değildir.",
  "Kelebekler ayaklarıyla tat alırlar.",
  "İneklerin en yakın arkadaşları vardır ve onlardan ayrıldıklarında stres yaşarlar.",
  "Dünyadaki en kısa savaş sadece 38 dakika sürmüştür (İngiltere - Zanzibar savaşı).",
  "Kedilerin köprücük kemiği yoktur, bu sayede kafalarının sığdığı her yerden geçebilirler.",
  "Venüs gezegeni güneş sisteminde saat yönünde dönen tek gezegendir.",
  "Zürafaların dilleri o kadar uzundur ki kendi kulaklarını temizleyebilirler.",
  "Eiffel Kulesi yazın sıcaktan genleşerek 15 cm kadar uzayabilir.",
  "Dünya üzerinde karınca nüfusu insan nüfusunun yaklaşık 1 milyon katıdır.",
  "Karıncayiyenlerin dişleri yoktur.",
  "İnsan DNA'sı %50 oranında bir muzun DNA'sı ile aynıdır.",
  "Bir kurşun kalemle ortalama 56 kilometre uzunluğunda bir çizgi çizilebilir.",
  "Köpeklerin burun izleri, insanların parmak izleri gibi tamamen kendilerine özgüdür.",
  "Jüpiter'in ve Satürn'ün gökyüzünden elmas yağdığı düşünülmektedir.",
  "Timsahlar dillerini dışarı çıkaramazlar.",
  "Dünyadaki oksijenin yarısından fazlası okyanuslardaki deniz yosunları tarafından üretilir.",
  "Bir karıncanın koku alma duyusu bir köpeğinki kadar güçlüdür.",
  "Baykuşlar gözlerini hareket ettiremezler, bu yüzden kafalarını çevirmek zorundadırlar.",
  "Her insanın dil izi de parmak izi gibi tamamen benzersizdir.",
  "Su aygırlarının teri pembe renklidir.",
  "Kutup ayılarının derisi aslında siyahtır ve tüyleri şeffaftır.",
  "Bukalemunların dilleri kendi vücutlarından iki kat daha uzundur.",
  "İnsan beyni, çalışırken 10 watt'lık bir ampulü yakacak kadar elektrik üretir.",
  "Yeryüzünde hiçbir sesin yankı yapmadığı tek yer ördek vakvaklamasıdır.",
  "Dünyanın en uzun ağacı Hyperion adlı bir sekoyadır ve boyu 115 metreden fazladır.",
  "İstakozların kanı mavidir.",
  "Kangurular geri geri yürüyemezler.",
  "Köpekbalıkları hastalanmayan nadir canlılardan biridir.",
  "Sıcak su, soğuk sudan daha hızlı donar (Mpemba etkisi).",
  "İnsan kalbi vücudun dışında bile atmaya devam edebilir çünkü kendi elektrik sistemine sahiptir.",
  "Dünyanın en küçük kuşu Arı Sinekkuşu'dur ve ağırlığı bir madeni paradan daha hafiftir.",
  "Gözlerimiz doğduğumuzdan beri aynı boyuttadır ancak burnumuz ve kulaklarımız büyümeye devam eder.",
  "Sivrisineklerin 47 tane dişi vardır.",
  "Devekuşlarının gözü beyinlerinden daha büyüktür.",
  "Bir insan hayatı boyunca ortalama olarak uykusunda 70 böcek ve 10 örümcek yutar.",
  "Dünyadaki en yaygın isim Muhammed'dir.",
  "İngiliz alfabesinde en çok kullanılan harf 'E' dir.",
  "Parmak izi olan tek primat insan değildir, koalaların da insanlara çok benzeyen parmak izleri vardır.",
  "Penguenler deniz suyunu içebilirler çünkü gözlerinin arkasında tuzu filtreleyen bir bez bulunur.",
  "Dünyanın en büyük çölü Sahra değil, Antarktika'dır.",
  "Satrançta ilk 4 hamle için 318 milyar farklı oynama ihtimali vardır.",
  "Elmalar suda yüzer çünkü %25'i havadan oluşur.",
  "Bir cam kırıldığında, çatlaklar saatte 4800 km hızla yayılır.",
  "Bir pire, kendi boyunun 200 katı yüksekliğe zıplayabilir.",
  "Leonardo da Vinci aynı anda bir eliyle yazı yazıp diğer eliyle resim çizebiliyordu.",
  "Okyanusların sadece %5'i keşfedilebilmiştir.",
  "Kediler hayatlarının %70'ini uyuyarak geçirirler.",
  "Dünyada insanlardan daha fazla plastik flamingo vardır.",
  "Dünyanın en derin yeri olan Mariana Çukuru, Everest Dağı'ndan daha derindir.",
  "Atlar ve inekler ayakta uyuyabilirler.",
  "Gülmek, stresi azaltan endorfin hormonunun salgılanmasını sağlar.",
  "Yunuslar uyurken beyinlerinin sadece yarısı dinlenir, diğer yarısı uyanık kalır.",
  "Bir damla deniz suyunda milyonlarca bakteri ve virüs bulunabilir.",
  "Mavi balinaların kalbi o kadar büyüktür ki, bir insan atardamarlarının içinde yüzebilir.",
  "Bambu, dünyadaki en hızlı büyüyen bitkidir; günde 90 cm uzayabilir.",
  "Çikolata, Aztekler zamanında para birimi olarak kullanılmıştır.",
  "Satürn'ün yoğunluğu sudan daha azdır; yani dev bir havuza koysanız yüzerdi.",
  "İlk çalar saat sadece sabah saat 4'te çalacak şekilde ayarlanabiliyordu.",
  "Yıldırım aynı yere iki kere düşmez inanışı yanlıştır; Empire State binasına yılda ortalama 23 kez yıldırım düşer.",
  "Kaju fıstığı aslında bir meyvenin sapıdır.",
  "Avustralya, Ay'dan daha geniştir.",
  "Bir kağıt parçasını 42 kez katlayabilseydiniz, kalınlığı Ay'a ulaşırdı.",
  "İnekler müzik dinlerken daha fazla süt üretirler.",
  "Filler zıplayamayan tek memelidir.",
  "Domuzlar fiziksel olarak gökyüzüne bakamazlar.",
  "Dünyadaki insanların %10'u solaktır.",
  "Kedilerin her bir kulağında 32 kas vardır.",
  "Denizyıldızlarının beyni yoktur.",
  "Hapşırırken gözlerinizi açık tutmak neredeyse imkansızdır.",
  "Bir insanın saç teli ortalama 3 kilo ağırlık taşıyabilir.",
  "Çilek, tohumları dışında olan tek meyvedir.",
  "Bir panda günde ortalama 12 saat bambu yer.",
  "Dünyadaki dillerin yarısından fazlası önümüzdeki 100 yıl içinde yok olma tehlikesiyle karşı karşıya.",
  "Uzayda ağladığınızda gözyaşlarınız dökülmez, yüzünüzde birikir.",
  "İnsan kemikleri çelikten yaklaşık beş kat daha dayanıklıdır.",
  "Kargalar yüzleri unutmazlar ve kindar olabilirler.",
  "Böcekler dünyanın toplam hayvan biyokütlesinin büyük bir kısmını oluşturur.",
  "Dünyada her saniye 4 bebek doğmaktadır.",
  "Bir insanın kalbi günde ortalama 100.000 kez atar.",
  "Zürafaların ses telleri yoktur.",
  "Mısır piramitleri inşa edilirken mamutlar hala dünya üzerinde yaşıyordu.",
  "Kutup ayıları solaktır.",
  "Dünyadaki suyun sadece %1'i içilebilir tatlı sudur.",
  "Güneş ışığının Dünya'ya ulaşması yaklaşık 8 dakika 20 saniye sürer.",
  "Mors alfabesinde 'SOS' herhangi bir kelimenin kısaltması değildir, sadece akılda kalıcı olduğu için seçilmiştir.",
  "Dünyanın en küçük memelisi olan yabanarısı yarasası sadece 2 gram ağırlığındadır.",
  "Köpekler rüya görebilirler.",
  "Bir insan gün boyunca ortalama 20.000 kez nefes alır.",
  "Fareler gıdıklandıklarında gülerler.",
  "Kar tanelerinin her biri benzersizdir.",
  "Kelebekler kırmızı, yeşil ve sarı renkleri görebilirler.",
  "Dünyanın en çok ziyaret edilen ülkesi Fransa'dır.",
  "Bir elma ağacının meyve vermesi 4-5 yıl sürebilir.",
  "Gökyüzünün mavi olmasının sebebi atmosferin mavi ışığı diğer renklerden daha fazla saçmasıdır.",
  "Altın o kadar esnektir ki, 1 gram altından 3 kilometre uzunluğunda bir tel çekilebilir.",
  "Gülümsemek için 17, kaş çatmak için ise 43 kas çalışır."
];

export const LOADING_STORIES = [
  "Veritabanındaki tozlar alınıyor...",
  "Kahve makinesi ısıtılıyor...",
  "Hamsterlar çarkta hızlanıyor...",
  "Pikseller yerlerine diziliyor...",
  "Algoritmalar son hazırlıklarını yapıyor...",
  "Hatalar (bug'lar) kapının dışına konuluyor...",
  "Sunucuya 'lütfen' deniliyor...",
  "Bulutlar biraz daha yukarı taşınıyor...",
  "Paketler gümrükten geçiyor...",
  "İnternet kablolarındaki düğümler çözülüyor...",
  "Veriler paketleniyor, kurdele takılıyor...",
  "Gereksiz noktalı virgüller ayıklanıyor...",
  "Yapay zeka dünyayı ele geçirmemeye ikna ediliyor...",
  "Ejderhalar sakinleştiriliyor...",
  "Boşluk karakterleri sayılıyor...",
  "Kodlar ütüleniyor...",
  "Binary ağacından meyveler toplanıyor...",
  "Bit'ler ve Byte'lar dans ediyor...",
  "Sunucu odasına vantilatör tutuluyor...",
  "Cache temizleniyor, ferahlık geliyor...",
  "API'lar el sıkışıyor...",
  "Veri trafiğinde ışıklar yeşile döndü...",
  "Uygulamanın ruhu şarj ediliyor...",
  "Sessiz olun, veriler uyuyor...",
  "Karanlık mod için piksellere gözlük dağıtılıyor...",
  "JSON verileri diyete sokuluyor...",
  "Fonksiyonlar içtima alıyor...",
  "CSS dosyaları taranıyor...",
  "Halı saha çizgileri boyanıyor...",
  "Kurbanlıklar tek tek seçiliyor...",
  "Hediye paketinin fiyonku bağlanıyor...",
  "Piksel tozları eleniyor...",
  "RAM'de yer açılıyor, süpürge sesine dikkat!",
  "Uzay-zaman sürekliliği korunuyor...",
  "Arka planda biri şarkı mırıldanıyor...",
  "Matrix'e giriş yapılıyor...",
  "Kırmızı hap mı, mavi hap mı? Karar veriliyor...",
  "Sabır testi başarıyla geçiliyor...",
  "Loading çubuğu boyanıyor...",
  "Gereksiz dosyalar geri dönüşüme gönderiliyor...",
  "Algoritma son virajı dönüyor...",
  "Veritabanı uykusundan uyandırılıyor...",
  "Sistemdeki örümcek ağları temizleniyor...",
  "Kodlar kahve molasından dönüyor...",
  "Piksellerin pası siliniyor...",
  "Arka plandaki orkestra akort yapıyor...",
  "Birkaç satır kodun gönlü alınıyor...",
  "Binary kodlar tercüme ediliyor...",
  "Veriler taze taze fırından çıkıyor...",
  "Güvenlik duvarı 'bizden biri' denilerek geçiliyor...",
  "Kuantum hesaplamalar yapılıyor (galiba)...",
  "Datalar arasında köprü kuruluyor...",
  "Hata ayıklayıcılar mesaiye başladı...",
  "Zaman makinesi 1 saniye ileriye ayarlanıyor...",
  "Sunucuya moral veriliyor...",
  "Uygulama esniyor ve uyanıyor...",
  "Sıfırlar ve birler sıraya giriyor...",
  "Router'lara yön tarifi veriliyor...",
  "Backend'den onay bekleniyor...",
  "Frontend süsleniyor...",
  "Tıklamalar sayılıyor...",
  "Düşünceler koda dökülüyor...",
  "Daha hızlı yüklenmek için nefes tutuluyor...",
  "Ekran kartına sevgi gösteriliyor...",
  "İşlemciye soğuk su dökülüyor...",
  "Veri madeninden cevherler çıkarılıyor...",
  "Yazılımın canı sıkılmasın diye müzik çalınıyor...",
  "Noktalı virgüllerin yeri kontrol ediliyor...",
  "Git commit'leri temizleniyor...",
  "Branch'ler birleştiriliyor...",
  "Kurban bayramına hazırlık yapılıyor...",
  "Halı sahada takımlar kuruluyor...",
  "Hediye analizi derinleşiyor...",
  "Veriler ışık hızıyla taşınıyor...",
  "Sistemdeki fazla boşluklar emiliyor...",
  "Kullanıcıya gülümseniyor :)",
  "Modern UI standartları uygulanıyor...",
  "Vektörler çiziliyor...",
  "Renk paleti karıştırılıyor...",
  "Gradientler yumuşatılıyor...",
  "Hover efektleri cilalanıyor...",
  "Media query'ler test ediliyor...",
  "Responsive tasarım ayarlanıyor...",
  "Z-index krizleri çözülüyor...",
  "Margin ve Padding savaşları bitti...",
  "Flexbox kutuları hizalıyor...",
  "Grid sistemi inşa ediliyor...",
  "Fontlar yükleniyor, okunabilirlik artıyor...",
  "İkonlar parlatılıyor...",
  "Mobil uyum kontrol ediliyor...",
  "Performans canavarı besleniyor...",
  "Siber saldırganlara 'dur' deniliyor...",
  "Portlar taranıyor...",
  "Dns kayıtları sorgulanıyor...",
  "Sertifikalar imzalanıyor...",
  "Şifreleme anahtarları üretiliyor...",
  "Veri sızıntılarına karşı tıkama yapılıyor...",
  "Sistem optimize ediliyor...",
  "Her şey hazır, son dokunuşlar yapılıyor...",
  "Yükleme tamamlanmak üzere, ayrılmayın!"
];
